"use strict";
/* ═══ NUTRITION ADRIEN — DONNÉES (23/08/2026, générées depuis adrien/nutrition/00-PROFIL-NUTRITION-ADRIEN.md v2) ═══
   Mode PRISE DE MASSE : cibles fixes 2900 kcal (pas de formule), hiérarchie GLUCIDES > LIPIDES > PROTÉINES.
   Recettes = les plats VALIDÉS d'Adrien avec quantités exactes et NIVEAUX DE PLAQUE (1/2/3, plaques fer sans four).
   Décisions du 24/08 (réponses aux questions ouvertes) : macros ESTIMÉES partout où Yazio manque (flags est/gEst),
   les 6 recettes héritées sont complétées en quantités estimées, beurre du pdj = option à cocher,
   shaker au lait d'amande (choix d'Adrien), féculent 100–200 g sec selon le plat (~150 g en général), zéro dinde.
   Interdits absolus du doc §4 respectés. */
var NUTA=(function(){

/* Cibles révisées 24/08 (2e vague) : journée idéale = 360 g gluc · 150 g prot · 80 g lip */
var CIBLES={kcal:2900,pMin:150,pMax:150,gMin:360,gMax:360,lMax:80,platKMin:900,platKMax:1200,platLMax:35,platGMin:130,platPMin:50};

/* Base SANS le beurre — le beurre est une option à cocher dans la Journée.
   parts = éléments sélectionnables un à un dans la Journée (retour Adrien 24/08 :
   « des fois pas le même nombre d'œufs, pas de banane, la compote-créatine part en snack »).
   def = quantités du pdj classique (3×78+4×57+105+90 ≈ 655 kcal). Le pancake protéiné
   (sa recette batch 🥞) peut AUSSI faire le petit-déj. */
var PDJ={id:'pdj',n:'Petit-déjeuner',emoji:'🍳',kcal:655,p:38,g:99,l:22,
 items:['3 œufs (brouillés ou au plat — pareil : 5 g de lipides par œuf)','4 tranches de pain complet seigle & graines','1 banane','1 compote — avec les 5 g de créatine dedans'],
 parts:[
  {id:'oeuf',n:'Œuf',emoji:'🥚',k:78,p:6.5,g:0.5,l:5,def:3,max:6},
  {id:'pain',n:'Tranche pain seigle & graines',emoji:'🍞',k:57,p:4,g:13,l:2,def:4,max:8},
  {id:'banane',n:'Banane',emoji:'🍌',k:105,p:1,g:25,l:0,def:1,max:2},
  {id:'compote',n:'Compote + créatine',emoji:'🍎',k:90,p:0,g:20,l:0,def:1,max:2},
  {id:'pancake',n:'Pancake protéiné',emoji:'🥞',k:149,p:9.2,g:21.5,l:2.7,def:0,max:6}],
 beurre:{n:'10–15 g de beurre',k:90,l:10}};

var SHAKER={id:'shaker',n:'Shaker (filet de sécurité)',emoji:'🥤',kcal:540,p:35,g:73,l:10,
 items:['300 ml lait d’amande (toujours — pas de lait demi-écrémé)','70 g flocons d’avoine','30 g whey vanille ou fraise','1 banane','40 g fruits rouges surgelés','5 g créatine si pas déjà prise']};

/* Recettes — s: [niveau, texte] · niveau : 'rc' rice cooker · 1/2/3 plaque · 0 hors feu / prépa */
var R=[
{id:'rizthon',n:'Riz sauté thon-œuf, sauce soja-sriracha',emoji:'🍚',plats:2,t:20,base:'riz',noswapf:true,kcal:1110,p:63,g:147,gEst:true,l:30,
 ing:['320 g riz thaï sec','280 g thon au naturel égoutté (2 boîtes)','4 œufs','1 oignon moyen émincé','1 carotte en fines rondelles','100 g champignons en lamelles','2 càs huile de tournesol','3 càs sauce soja','2 càc miel','2 càc sriracha','1 càc ail en poudre','1 càc paprika fumé','1 càc huile de sésame (hors du feu)'],
 s:[['rc','Riz au rice cooker.'],
    [0,'Presse le thon dans le couvercle pour retirer un maximum d’eau. Émiette grossièrement.'],
    [0,'Mélange la sauce dans un bol : soja, miel, sriracha, ail, paprika.'],
    [3,'1 càs d’huile, chauffe 1–2 min. Oignon + carotte 3 min.'],
    [2,'Champignons, 4 min jusqu’à évaporation de leur eau.'],
    [2,'Pousse sur le côté, œufs battus dans l’espace libre, brouille 1 min, mélange.'],
    [3,'Riz cuit + 2e càs d’huile, 3–4 min en écrasant les paquets contre la poêle.'],
    [2,'Thon émietté, mélange 1 min SEULEMENT — sinon ça part en bouillie.'],
    [2,'Verse la sauce, 1–2 min. Huile de sésame HORS du feu.']],
 notes:['Conservation : exception à la règle — le riz sauté est sec, tout peut aller dans la même boîte.']},
{id:'steakdegl',n:'Steak haché, sauce déglacée (0 lipide)',emoji:'🥩',plats:1,t:15,base:'riz',kcal:880,p:50,g:135,gEst:true,l:20,
 ing:['150 g riz thaï sec','2 steaks hachés surgelés 10 % MG','6 càs d’eau','¼ cube de bouillon bœuf','2 càs sauce soja','1 càc miel','1 càc ail en poudre','1 càc moutarde à l’ancienne','poivre'],
 s:[['rc','Riz au rice cooker.'],
    [3,'Steaks SURGELÉS, sans huile : 4 min par face sans toucher.'],
    [0,'Sors les steaks. VIDE l’eau et le gras rendus.'],
    [2,'Verse eau + bouillon émietté. Gratte les sucs bruns au fond.'],
    [2,'Soja, miel, ail, moutarde, poivre. Réduis 2 min.'],
    [2,'Hache les steaks à la spatule, remets-les 1 min. Verse sur le riz.']],
 notes:['Macros recalculées pour le steak 10 % (24/08) — un peu court en kcal : monte le riz à 180 g si tu as faim.','La sauce elle-même : ~50 kcal, 0 g de lipides.','Variante piquante : remplace la moutarde par 1 càc de gochujang.']},
{id:'poivrerapide',n:'Steak haché sauce poivre rapide',emoji:'🥩',plats:1,t:12,base:'riz',kcal:1070,p:52,g:120,l:35,est:true,cremeux:true,
 ing:['150 g riz thaï sec','2 steaks hachés 10 %','4 càs sauce poivre','1 càs sauce soja','3 càs d’eau','1 càc ail en poudre'],
 s:[['rc','Riz au rice cooker.'],
    [2,'Steaks hachés à la spatule directement dans la poêle.'],
    [2,'Ajoute sauce poivre, soja, eau, ail.'],
    [2,'Mélange 2 min. Verse sur le riz.']],
 warn:'Macros estimées (validées le 24/08) — à affiner si tu sors les valeurs Yazio un jour.',
 notes:['Le soja + l’ail empêchent la sauce poivre en pot d’avoir un goût plat d’industriel. 10 secondes de plus, ne pas les sauter.','Sauce poivre = ton kiff, mais 1×/semaine max.']},
{id:'pouletcreme',n:'Poulet crème-champignons',emoji:'🍗',plats:2,t:25,base:'riz',kcal:1070,p:70,g:135,gEst:true,l:28,cremeux:true,
 ing:['300 g riz thaï sec','500 g filet de poulet découpé','1 oignon émincé','250 g champignons en lamelles','150 g crème légère','2 càs huile de tournesol','1 càs sauce soja','1 càc moutarde à l’ancienne','2 càc paprika fumé (1 poulet + 1 sauce)','2 càc ail en poudre (1 poulet + 1 sauce)','½ càc cumin','sel, poivre'],
 s:[['rc','Riz au rice cooker.'],
    [0,'Saladier : poulet + 1 càc paprika + 1 càc ail + ½ càc cumin + sel + poivre. 30 secondes à la main.'],
    [3,'1 càs d’huile. Poulet EN 2 FOIS, 4–5 min par fournée sans toucher. Réserve.'],
    [2,'1 càs d’huile. Oignon 3 min, puis champignons 4–5 min jusqu’à évaporation de leur eau.'],
    [1,'Crème + soja + moutarde + 1 càc paprika + 1 càc ail. Remets le poulet, mélange 2 min. JAMAIS bouillir.']],
 notes:['Conservation : riz et sauce dans DEUX boîtes séparées.','Réchauffage de la crème : poêle niveau 1 + 1 càs d’eau — jamais micro-ondes, elle tranche.']},
{id:'capellini',n:'Capellini bœuf-champignons crème',emoji:'🍝',plats:1,t:20,base:'pates',kcal:955,p:64,g:124,gEst:true,l:27,cremeux:true,
 ing:['150 g capellini secs','2 steaks hachés surgelés 10 %','150 g champignons','80 g crème légère épaisse','1 càs sauce soja','1 càc paprika fumé','1 càc ail en poudre'],
 s:[[3,'Eau à bouillir, sale généreusement.'],
    [3,'Steaks surgelés, sans huile : 4 min par face sans toucher.'],
    [0,'Sors-les. Garde 1 càs du gras rendu, jette le reste.'],
    [2,'Champignons 5 min jusqu’à évaporation.'],
    [1,'Crème + soja + paprika + ail, 2 min. Jamais bouillir.'],
    [3,'⚠️ Les capellini cuisent en 2–3 min MAX. Goûte à 2 min. Garde une louche d’eau de cuisson.'],
    [1,'Hache les steaks à la spatule dans la sauce, mélange, verse sur les pâtes.']],
 notes:['Macros recalculées pour le steak 10 % (24/08).','Version 2 PLATS : 300 g capellini · 4 steaks · 250 g champignons · 160 g crème · 2 càs soja · 2 càc paprika · 2 càc ail → ~970 kcal · 64 g prot · 28 g lip par plat. Steaks en 2 fois.','Pâtes cuites au dernier moment pour chaque repas, ou 1 càs d’huile dans la boîte avant le frigo.','Les capellini se ratent en 30 secondes — les spaghetti pardonnent plus (8–9 min).']},
{id:'porcsaute',n:'Porc sauté haricots verts, riz doré à l’œuf',emoji:'🥘',plats:1,t:25,base:'riz',noswapf:true,kcal:1229,p:95,g:98,l:51,
 ing:['95 g riz thaï sec','335 g émincé de porc','2 œufs','220 g haricots verts égouttés (½ conserve)','½ oignon','1 càs huile de tournesol','3 càs sauce soja','1 càc miel','1 càc ail en poudre','1 càs sriracha','1 càc huile de sésame (hors du feu)','sel, poivre, 1 càc paprika'],
 s:[['rc','Riz au rice cooker.'],
    [3,'Huile bien chaude. Porc EN 2 FOIS, 4–5 min par fournée sans toucher. Sel, poivre, paprika. Réserve.'],
    [2,'Oignon 3 min. Haricots verts égouttés, 4 min.'],
    [2,'Pousse sur le côté, œufs battus, brouille 1 min, mélange.'],
    [3,'Riz cuit, 3 min en écrasant les paquets.'],
    [2,'Remets le porc, verse la sauce, 2 min. Huile de sésame HORS du feu.']],
 warn:'51 g de lipides (valeurs Yazio réelles) — au-dessus de la règle des 35 g. À équilibrer avec un dîner sauce soja.',
 notes:['Macros = valeurs Yazio réelles.']},
{id:'ffpoivre',n:'Faux-filet sauce poivre-crème, riz et champignons',emoji:'🥩',plats:1,t:25,base:'riz',kcal:1257,p:64.5,g:163,l:39,cremeux:true,
 ing:['180 g riz thaï sec','175 g faux-filet (gras laissé en place)','150 g champignons en lamelles','40 g oignon émincé','100 g crème légère épaisse','3 càs sauce poivre','1 càs sauce soja','1 càc ail en poudre','1 càc paprika fumé','1 càs d’eau','sel, poivre'],
 s:[[0,'SORS le faux-filet du frigo 20–30 min avant. Lance le riz.'],
    [0,'Sale et poivre les deux faces. Ne retire pas le gras.'],
    [3,'Poêle VIDE, SANS huile : 4–5 min à blanc. Test de la goutte d’eau (elle doit crépiter en moins d’une seconde).'],
    [3,'Pose la viande, NE TOUCHE PLUS. 2 min pour saignant. Retourne UNE seule fois, 2 min. Sors-la.'],
    [0,'REPOS 3 min sur une assiette, assiette retournée par-dessus sans serrer. Pendant ce temps : la sauce.'],
    [2,'Garde le gras rendu. Oignon 2 min, puis champignons 5 min. Gratte les sucs.'],
    [1,'Crème + sauce poivre + soja + ail + paprika + eau. 2 min. Jamais bouillir.'],
    [0,'Coupe la viande dans le sens CONTRAIRE des fibres. Riz, sauce, viande dessus. Ajoute le jus du repos.']],
 warn:'39 g de lipides — ton kiff sauce poivre, 1×/semaine max.',
 notes:['Macros = valeurs Yazio réelles.']},
{id:'ffsoja',n:'Faux-filet saignant, haricots verts sauce soja, riz',emoji:'🥩',plats:1,t:25,base:'riz',star:true,kcal:1045,p:52,g:160,l:16,
 ing:['180 g riz thaï sec','150 g faux-filet, bord de gras RETIRÉ','220 g haricots verts égouttés','60 g oignon émincé','3 càs sauce soja','1 càc miel','1 càc ail en poudre','1 càs sriracha','2 càs d’eau'],
 s:[[0,'Sors la viande 20–30 min avant. Lance le riz.'],
    [0,'Retire le bord de gras. Sale, poivre. Mélange la sauce dans un bol.'],
    [3,'Poêle vide, sans huile : 4–5 min à blanc.'],
    [3,'Saisis 2 min par face. Sors la viande.'],
    [0,'REPOS 3 min.'],
    [2,'Oignon 2 min, gratte les sucs. Puis haricots verts 4 min.'],
    [2,'Verse la sauce, 1 min.'],
    [0,'Coupe la viande en lanières. Dresse.']],
 notes:['⭐ MEILLEUR RATIO GLUCIDES/LIPIDES du répertoire : 160 g de glucides pour 16 g de lipides.']},
{id:'rizboeuf',n:'Riz sauté au bœuf, champignons et œuf',emoji:'🍚',plats:2,t:30,base:'riz',star:true,noswapf:true,kcal:1055,p:56,g:155,l:20,
 ing:['360 g riz thaï sec','300 g bœuf attendri/saumuré en lanières','300 g champignons en lamelles','120 g oignon émincé','2 œufs','5 càs sauce soja','2 càc miel','2 càc ail en poudre','2 càs sriracha','1 càc paprika fumé','4 càs d’eau','PAS DE SEL (viande déjà saumurée)'],
 s:[['rc','Riz au rice cooker.'],
    [0,'Bœuf en lanières d’1 cm, sens contraire des fibres. Poivre + paprika. ÉPONGE au papier absorbant — la viande saumurée est gorgée d’eau.'],
    [0,'Mélange la sauce dans un bol.'],
    [3,'Poêle vide, sans huile, 4 min à blanc. Bœuf EN 2 FOIS, 3 min par fournée sans toucher. Réserve.'],
    [2,'Garde le gras rendu. Oignon 3 min, puis champignons 6 min jusqu’à évaporation COMPLÈTE.'],
    [2,'Pousse sur le côté, œufs battus, brouille 1 min, mélange.'],
    [3,'Riz cuit, 4 min en écrasant les paquets.'],
    [2,'Remets le bœuf + la sauce, 2 min. GOÛTE avant de saler.']],
 notes:['Conservation : tout dans la même boîte (riz sauté = sec). Réchauffage micro-ondes 2–3 min + 1 càs d’eau.']},
{id:'pouletrose',n:'Poulet sauce crème-tomate-basilic, penne',emoji:'🍝',plats:2,t:20,base:'pates',kcal:1175,p:85,g:151,l:22,cremeux:true,
 ing:['400 g pâtes sèches (penne ou fusilli)','500 g filet de poulet en morceaux','100 g crème légère','60 g concentré de tomate','60 g oignon émincé','1 càs huile de tournesol','1 càs sauce soja','2 càc ail en poudre','1 càc paprika fumé','1 càc herbes de Provence','10 g basilic frais ciselé','200 ml d’eau de cuisson des pâtes'],
 s:[[0,'Coupe le poulet en morceaux égaux. Sel, poivre, paprika.'],
    [3,'Eau des pâtes, sale généreusement.'],
    [3,'Huile. Poulet EN 2 FOIS, 5 min par fournée sans toucher. Réserve.'],
    [3,'Cuis les pâtes. GARDE une louche d’eau de cuisson.'],
    [2,'Dans la poêle du poulet : oignon 3 min. Puis concentré de tomate, 1 min pour le TORRÉFIER — ça enlève son goût métallique.'],
    [1,'Crème + soja + ail + herbes + 200 ml d’eau de cuisson. 2–3 min. Jamais bouillir.'],
    [0,'Remets le poulet 1 min, COUPE le feu, puis le basilic.']],
 notes:['Volume de sauce corrigé après ton retour : 200 ml d’eau de cuisson, pas 8 càs.','Le basilic cuit perd tout — toujours hors du feu.']},
{id:'pouletmoutarde',n:'Poulet sauce moutarde à l’ancienne, pâtes',emoji:'🍝',plats:2,t:20,base:'pates',kcal:1170,p:85,g:143,l:24,cremeux:true,
 ing:['400 g pâtes sèches','500 g filet de poulet','100 g crème légère épaisse','3 càs moutarde à l’ancienne','200 ml d’eau de cuisson des pâtes','½ cube de bouillon émietté','1 càs sauce soja','2 càc ail en poudre','1 càc herbes de Provence','1 càs huile de tournesol','poivre'],
 s:[[3,'Poulet EN 2 FOIS, réserve. GARDE la poêle avec les sucs.'],
    [2,'Eau de cuisson + bouillon. Gratte le fond. Réduis 3–4 min (perdre ~⅓ du volume).'],
    [1,'Crème, moutarde, soja, ail, herbes. 2–3 min. AUCUNE bulle.'],
    [1,'Remets le poulet, 1 min.'],
    [0,'Verse sur les pâtes.']],
 notes:['Si trop liquide : 2 min de plus au niveau 1 sans couvercle.']},
{id:'steakcremepoivre',n:'Steaks hachés, riz, sauce crème-poivre',emoji:'🍛',plats:1,t:15,base:'riz',kcal:1170,p:58,g:163,l:38,cremeux:true,
 ing:['200 g riz thaï sec','2 steaks hachés 10 % (Intermarché)','80 g crème légère épaisse','3 càs sauce poivre','100 ml d’eau','1 càs sauce soja','1 càc ail en poudre','1 càc paprika fumé','poivre du moulin'],
 s:[[3,'Steaks surgelés, sans huile : 4 min par face sans toucher.'],
    [0,'Sors-les. VIDE l’eau et le gras rendus.'],
    [2,'Verse les 100 ml d’eau, gratte les sucs. Réduis 2 min.'],
    [1,'Crème + sauce poivre + soja + ail + paprika. 2–3 min. AUCUNE bulle.'],
    [1,'Hache les steaks à la spatule, remets 1 min. Verse sur le riz.']],
 warn:'38 g de lipides (recalculé steak 10 %, 24/08) — reste le plat le plus gras du répertoire. À compenser sur l’autre repas avec une sauce soja.'},
/* ── Héritées, validées — quantités + macros ESTIMÉES (décision 24/08 : on estime en attendant Yazio) ── */
{id:'pouletsojasesame',n:'Poulet soja-sésame',emoji:'🍗',plats:1,t:20,base:'riz',est:true,kcal:1055,p:68,g:124,l:30,
 ing:['150 g riz thaï sec','250 g filet de poulet en morceaux','1 càs huile de tournesol','3 càs sauce soja','1 càc miel','1 càc ail en poudre','1 càs sriracha','1 càs huile de sésame (hors du feu)'],
 s:[['rc','Riz au rice cooker.'],
    [0,'Mélange la sauce dans un bol : soja, miel, ail, sriracha.'],
    [3,'1 càs d’huile bien chaude. Poulet 4–5 min sans toucher, retourne une seule fois.'],
    [2,'Verse la sauce, 1–2 min pour napper.'],
    [0,'Huile de sésame HORS du feu. Verse sur le riz.']],
 warn:'Macros estimées — à confirmer avec Yazio.'},
{id:'porcmoutarde',n:'Émincés de porc moutarde',emoji:'🐷',plats:1,t:20,base:'pates',est:true,cremeux:true,kcal:1330,p:87,g:113,l:42,
 ing:['150 g pâtes sèches','320 g émincé de porc','60 g crème légère épaisse','2 càs moutarde à l’ancienne','100 ml d’eau de cuisson des pâtes','½ oignon émincé','1 càs huile de tournesol','1 càs sauce soja','1 càc paprika fumé','1 càc herbes de Provence','poivre'],
 s:[[3,'Eau des pâtes, sale généreusement. Cuis les pâtes, GARDE une louche d’eau de cuisson.'],
    [3,'1 càs d’huile. Porc EN 2 FOIS, 4–5 min par fournée sans toucher. Réserve.'],
    [2,'Oignon 3 min dans la poêle du porc, gratte les sucs.'],
    [1,'Crème + moutarde + soja + paprika + herbes + 100 ml d’eau de cuisson. 2–3 min, JAMAIS bouillir.'],
    [1,'Remets le porc 1 min. Verse sur les pâtes.']],
 warn:'~42 g de lipides estimés — au-dessus des 35 g : équilibre l’autre repas du jour avec une sauce soja.'},
{id:'pouletcumin',n:'Poulet cumin croustillant',emoji:'🍗',plats:1,t:25,base:'pates',est:true,kcal:1125,p:77,g:144,l:26,
 ing:['150 g pâtes sèches','250 g filet de poulet en morceaux','20 g maïzena + 1 càc cumin + 1 càc paprika fumé (enrobage)','1 càs huile de tournesol','2 càs sauce soja','1 càs miel','2 càc huile de sésame','1 càc ail en poudre'],
 s:[[3,'Eau des pâtes, sale généreusement.'],
    [0,'Enrobe le poulet : maïzena + cumin + paprika, dans un saladier, 30 secondes à la main.'],
    [3,'Huile bien chaude. Poulet 4–5 min SANS toucher pour former la croûte, retourne une fois.'],
    [0,'Sauce dans un bol : soja + miel + huile de sésame + ail.'],
    [0,'RÈGLE ABSOLUE : la sauce va sur les PÂTES, le poulet croustillant PAR-DESSUS — jamais mélangé dedans.']],
 warn:'Macros estimées — à confirmer avec Yazio.'},
{id:'cabillaudcurry',n:'Cabillaud curry-coco',emoji:'🐟',plats:1,t:20,base:'riz',est:true,kcal:1120,p:67,g:147,l:24,
 ing:['180 g riz thaï sec','300 g cabillaud','150 ml lait de coco Kara','1 càc curry','1 càs sauce soja','1 càc miel','1 càc ail en poudre'],
 s:[['rc','Riz au rice cooker.'],
    [1,'Lait de coco + curry + soja + miel + ail. Chauffe doucement — niveau 1 UNIQUEMENT.'],
    [1,'Pose le cabillaud dans la sauce, couvre si possible, 8–10 min. Il est cuit quand il s’émiette à la fourchette.'],
    [0,'Verse sur le riz.']],
 warn:'Macros estimées — à confirmer avec Yazio.',
 notes:['Bonus oméga-3 : vise aussi 2 boîtes de maquereau/sardines par semaine — ton trou nutritionnel identifié.']},
{id:'croustibat',n:'Croustibat soja-coco',emoji:'🐠',plats:1,t:15,base:'riz',est:true,noswapf:true,kcal:1200,p:42,g:177,l:35,
 ing:['9 Croustibat Findus','150 g riz thaï sec','60 ml lait de coco Kara','2 càs sauce soja','1 càc miel','½ càs huile de tournesol'],
 s:[['rc','Riz au rice cooker.'],
    [2,'½ càs d’huile, Croustibat 3–4 min par face jusqu’à bien dorés.'],
    [1,'Sauce : lait de coco + soja + miel, 1–2 min.'],
    [0,'La sauce va sur le riz SEUL — JAMAIS sur le pané (règle : rien de croustillant dans la sauce).']],
 warn:'Macros estimées — pile au plafond des 35 g de lipides. Pas d’autre source de gras sur ce repas.'},
{id:'porcgochujang',n:'Porc gochujang',emoji:'🐷',plats:2,t:20,base:'riz',est:true,kcal:1005,p:53,g:130,l:21,
 ing:['300 g riz thaï sec','400 g émincé de porc','2 càs gochujang','2 càs sauce huîtres','2 càs sauce soja','1 càc sucre + 1 càc miel (⚠️ réduits de moitié — ta note)','3 gousses d’ail hachées','1 càs huile de tournesol','1 càc huile de sésame (hors du feu)'],
 s:[['rc','Riz au rice cooker.'],
    [0,'Sauce dans un bol : gochujang + huîtres + soja + sucre + miel + ail.'],
    [3,'1 càs d’huile. Porc EN 2 FOIS, 4–5 min par fournée sans toucher.'],
    [2,'Remets tout le porc, verse la sauce, 2 min pour napper.'],
    [0,'Huile de sésame HORS du feu. Verse sur le riz.']],
 warn:'Macros estimées (par plat) — à confirmer avec Yazio.'},
/* ── Vague du 24/08 — 9 plats validés par Adrien (macros estimées) + SA recette de pancakes ── */
{id:'teriyaki',n:'Poulet teriyaki maison, riz',emoji:'🍗',plats:1,t:20,base:'riz',est:true,kcal:1030,p:68,g:155,l:12,
 ing:['180 g riz thaï sec','250 g filet de poulet en morceaux','4 càs sauce soja','1 càs + 1 càc miel','1 càc ail en poudre','4 càs d’eau','1 càc huile de tournesol','sésame doré (option, hors du feu)'],
 s:[['rc','Riz au rice cooker.'],
    [0,'Sauce dans un bol : soja + miel + eau + ail.'],
    [3,'1 càc d’huile. Poulet 4–5 min sans toucher, retourne une fois.'],
    [2,'Verse la sauce, laisse RÉDUIRE 2–3 min jusqu’à un sirop qui nappe le poulet.'],
    [0,'Verse sur le riz, sésame par-dessus.']],
 notes:['La sauce = soja + miel réduits : 0 lipide. Ton meilleur profil gluc/lip du répertoire avec le faux-filet soja.']},
{id:'porcsriracha',n:'Porc sriracha-miel caramélisé, riz',emoji:'🐷',plats:1,t:18,base:'riz',est:true,kcal:1050,p:68,g:150,l:18,
 ing:['170 g riz thaï sec','300 g émincé de porc','2 càs sriracha','1 càs miel','2 càs sauce soja','1 càc ail en poudre','½ oignon émincé','1 càs huile de tournesol'],
 s:[['rc','Riz au rice cooker.'],
    [0,'Sauce dans un bol : sriracha + miel + soja + ail.'],
    [3,'Huile bien chaude. Porc EN 2 FOIS, 4–5 min par fournée sans toucher. Réserve.'],
    [2,'Oignon 2–3 min dans la même poêle.'],
    [2,'Remets le porc, verse la sauce, 2 min — le miel caramélise, ça doit napper.'],
    [0,'Verse sur le riz.']]},
{id:'pouletmielmout',n:'Poulet miel-moutarde sans crème, pâtes',emoji:'🍗',plats:1,t:20,base:'pates',est:true,kcal:1050,p:72,g:145,l:16,
 ing:['170 g pâtes sèches','250 g filet de poulet en morceaux','2 càs moutarde à l’ancienne','1 càs miel','100 ml d’eau de cuisson des pâtes','1 càs sauce soja','1 càc ail en poudre','1 càc herbes de Provence','1 càs huile de tournesol'],
 s:[[3,'Pâtes dans la CASSEROLE (sale généreusement) — la poêle reste libre pour le reste. GARDE une louche d’eau de cuisson.'],
    [3,'Huile. Poulet 4–5 min sans toucher. Réserve.'],
    [2,'Déglace : 100 ml d’eau de cuisson dans la poêle chaude, gratte les sucs.'],
    [2,'Moutarde + miel + soja + ail + herbes. Réduis 2 min.'],
    [1,'Remets le poulet 1 min. Verse sur les pâtes.']],
 notes:['La sauce du plat « poulet moutarde » mais SANS les 100 g de crème : même goût moutarde-miel, 3× moins de lipides.']},
{id:'porcaigredoux',n:'Porc à l’aigre-douce et oignons, riz',emoji:'🐷',plats:1,t:18,base:'riz',est:true,kcal:1080,p:70,g:150,l:22,
 ing:['170 g riz thaï sec','300 g émincé de porc','5 càs sauce aigre-douce','1 oignon émincé','1 càs sauce soja','1 càc sriracha (option)','1 càs huile de tournesol'],
 s:[['rc','Riz au rice cooker.'],
    [3,'Huile. Porc EN 2 FOIS, 4–5 min par fournée. Réserve.'],
    [2,'Oignon 3 min, gratte les sucs.'],
    [2,'Remets le porc + aigre-douce + soja + sriracha, 2 min.'],
    [0,'Verse sur le riz.']],
 notes:['La sauce aigre-douce du commerce = 0 lipide — enfin utilisée dans un plat complet.']},
{id:'bolo',n:'Bolognaise express au steak 10 %',emoji:'🍝',plats:1,t:20,base:'pates',est:true,kcal:1060,p:62,g:150,l:22,
 ing:['180 g pâtes sèches','2 steaks hachés 10 %','½ oignon émincé','200 g sauce tomate','1 càs concentré de tomate','1 càc ail en poudre','1 càc herbes de Provence','1 càc huile d’olive (hors du feu)'],
 s:[[3,'Pâtes dans la casserole, sale généreusement.'],
    [3,'Steaks émiettés à la spatule, SANS huile, 4–5 min.'],
    [2,'Oignon 3 min avec la viande.'],
    [2,'Concentré de tomate, 1 min pour le TORRÉFIER (sinon goût métallique).'],
    [2,'Sauce tomate + ail + herbes, 3–4 min.'],
    [0,'Sur les pâtes, filet d’huile d’olive HORS du feu.']]},
{id:'velouteschampi',n:'Poulet, sauce champignons mixée au Ninja, pâtes',emoji:'🍄',plats:1,t:25,base:'pates',est:true,kcal:1080,p:75,g:145,l:20,
 ing:['170 g pâtes sèches','250 g filet de poulet en morceaux','250 g champignons en lamelles','½ oignon émincé','50 g crème légère épaisse','100 ml d’eau de cuisson des pâtes','1 càs sauce soja','1 càc paprika fumé','1 càc ail en poudre','1 càs huile de tournesol'],
 s:[[3,'Pâtes dans la casserole. GARDE une louche d’eau de cuisson.'],
    [3,'Huile. Poulet 4–5 min. Réserve.'],
    [2,'Oignon 3 min, puis champignons 5–6 min jusqu’à évaporation.'],
    [0,'BLENDER : champignons/oignon + crème + eau de cuisson + soja + paprika + ail. Mixe 30 s = une GROSSE sauce onctueuse avec 2× moins de crème.'],
    [1,'Sauce de retour dans la poêle + poulet, 2 min. Jamais bouillir.'],
    [0,'Verse sur les pâtes.']],
 notes:['L’astuce Ninja : le volume vient des champignons mixés, pas de la crème — 50 g suffisent au lieu de 100–150.']},
{id:'rizcantonais',n:'Riz cantonais au poulet',emoji:'🍚',plats:1,t:20,base:'riz',est:true,noswapf:true,kcal:1050,p:70,g:145,l:22,
 ing:['160 g riz thaï sec','250 g filet de poulet en dés','2 œufs','½ oignon émincé','1 carotte en petits dés','100 g champignons en lamelles','2 càs sauce soja','1 càc miel','1 càs sriracha','1 càs huile de tournesol','1 càc huile de sésame (hors du feu)'],
 s:[['rc','Riz au rice cooker.'],
    [0,'Sauce dans un bol : soja + miel + sriracha.'],
    [3,'Huile. Poulet 4–5 min sans toucher. Réserve.'],
    [2,'Oignon + carotte 3 min, puis champignons 4 min.'],
    [2,'Pousse sur le côté, œufs battus, brouille 1 min, mélange.'],
    [3,'Riz cuit, 3–4 min en écrasant les paquets.'],
    [2,'Remets le poulet, verse la sauce, 2 min. Huile de sésame HORS du feu.']],
 notes:['La variante POULET de tes riz sautés (tu avais thon, bœuf et porc — jamais poulet).']},
{id:'steakcheval',n:'Steak à cheval, riz, sauce déglacée',emoji:'🥩',plats:1,t:15,base:'riz',est:true,kcal:1010,p:63,g:140,l:26,
 ing:['160 g riz thaï sec','2 steaks hachés 10 %','1 œuf','6 càs d’eau + ¼ cube bouillon bœuf','2 càs sauce soja','1 càc moutarde à l’ancienne','1 càc miel','1 càc ail en poudre'],
 s:[['rc','Riz au rice cooker.'],
    [3,'Steaks surgelés sans huile, 4 min par face. Sors-les, vide le gras.'],
    [2,'DÉGLACE : eau + bouillon dans la poêle chaude, gratte les sucs bruns — c’est tout ce que « déglacer » veut dire. 2 min, 0 lipide.'],
    [2,'Soja + moutarde + miel + ail, réduis 2 min. Remets les steaks 1 min.'],
    [2,'Pousse sur le côté, œuf AU PLAT 2 min.'],
    [0,'Dressage : riz, steaks sauce, œuf par-dessus.']]},
{id:'omeletteXXL',n:'Omelette XXL paprika-champignons + toasts',emoji:'🍳',plats:1,t:15,est:true,kcal:885,p:44,g:90,l:39,
 ing:['4 œufs','150 g champignons en lamelles','½ oignon émincé','1 càc paprika fumé','1 càc huile d’olive','4 tranches de pain complet seigle & graines (grillées)','1 banane','1 compote en dessert'],
 s:[[2,'Huile. Oignon 3 min, puis champignons 4–5 min jusqu’à évaporation.'],
    [0,'Bats les œufs + paprika + sel + poivre. Lance les toasts au grille-pain.'],
    [1,'Verse les œufs sur les légumes. Cuisson DOUCE 3–4 min — baveux dessus, pris dessous.'],
    [0,'Sers avec les toasts, banane + compote en dessert.']],
 warn:'~39 g de lipides (œufs + pain aux graines) — équilibre le déjeuner ce jour-là. Monte à 5–6 toasts pour viser 1000 kcal.'},
{id:'pancakes',n:'Pancakes protéinés de la semaine',emoji:'🥞',plats:1,batch:15,t:35,kcal:149,p:9.2,g:21.5,l:2.7,
 ing:['300 ml lait','240 g skyr','2 gros œufs (ou 3 petits)','2 bananes bien mûres','1 càs miel','180 g flocons d’avoine','90 g farine','55 g whey (blueberry ou autre)','7 g levure chimique','1 càc cannelle','1 pincée de sel','55 g fruits rouges surgelés'],
 s:[[0,'BLENDER 45 s : lait + skyr + œufs + bananes + avoine.'],
    [0,'Ajoute miel + farine + whey + levure + cannelle + sel. PULSE 5–10 s SEULEMENT (plus = pancakes caoutchouc).'],
    [0,'Incorpore les fruits rouges à la cuillère DIRECTEMENT dans le blender (3–4 mouvements). REPOS 10 min — tout reste dans le blender jusqu’à la cuisson.'],
    [2,'Grosse louche versée depuis le blender. Attends les bulles sur TOUTE la surface (~3 min), retourne UNE fois, 2 min.'],
    [0,'Pâte trop épaisse après le repos ? Garde 50 ml de lait à côté pour détendre.']],
 notes:['TA recette (24/08, recalibrée 01/09) : quantités ramenées à ~15 pancakes (l’ancien batch en faisait ~25, beaucoup trop). Macros MESURÉES par pancake : 149 kcal · 9,2 g prot · 21,5 g gluc (2,8 fibres) · 2,7 g lip.','Le lait et le skyr sont MÉLANGÉS dans la pâte — conforme à ta règle (pas de laitage pur).','Batch de la semaine : tout cuire, boîte au frigo, à manger petit à petit. Ajoute-les à ta Journée via le snack 🥞.']},
/* ── VAGUE 2 (24/08 soir) — 19 plats, 6 filons validés : poissons · nouveaux féculents · skyr · froid · bœuf/veau/crevettes · stock ── */
{id:'saumonteriyaki',n:'Saumon teriyaki, riz',emoji:'🐟',plats:1,t:18,base:'riz',est:true,kcal:1065,p:52,g:150,l:28,
 ing:['170 g riz thaï sec','200 g pavé de saumon','3 càs sauce soja','1 càs miel','1 càc ail en poudre','3 càs d’eau','sésame doré (option)'],
 s:[['rc','Riz au rice cooker.'],
    [0,'Sauce dans un bol : soja + miel + eau + ail.'],
    [3,'Poêle SANS huile (le saumon rend son gras). Côté peau 4 min sans toucher.'],
    [2,'Retourne, 2–3 min. Verse la sauce, laisse réduire 1–2 min en nappant.'],
    [0,'Sur le riz, sésame par-dessus. Oméga-3 : c’est exactement ce qu’il te faut 2×/sem.']]},
{id:'sardinespates',n:'Pâtes ail-tomate aux sardines',emoji:'🐟',plats:1,t:15,base:'pates',est:true,kcal:1030,p:57,g:145,l:23,
 ing:['180 g pâtes sèches','2 boîtes de sardines égouttées','200 g sauce tomate','1 càc ail en poudre','1 càc herbes de Provence','1 càc sriracha (option)','½ oignon émincé'],
 s:[[3,'Pâtes dans la casserole, sale généreusement.'],
    [2,'Oignon 3 min à sec ou avec 1 càc de l’huile des sardines.'],
    [2,'Sauce tomate + ail + herbes + sriracha, 3 min.'],
    [1,'Sardines émiettées grossièrement, 1 min juste pour réchauffer (elles se défont vite).'],
    [0,'Verse sur les pâtes.']],
 notes:['La boîte de sardines = le geste oméga-3 le moins cher et le plus rapide qui existe. Vise 2 plats poisson gras/semaine.']},
{id:'maquereaurizdore',n:'Riz doré au maquereau et œufs',emoji:'🐟',plats:1,t:20,base:'riz',est:true,noswapf:true,kcal:1090,p:57,g:135,l:34,
 ing:['160 g riz thaï sec','1 boîte de maquereau égoutté (~170 g)','2 œufs','½ oignon émincé','2 càs sauce soja','1 càs sriracha','1 càc ail en poudre','1 càc paprika fumé'],
 s:[['rc','Riz au rice cooker.'],
    [2,'Oignon 3 min — pas besoin d’huile, le maquereau est gras.'],
    [2,'Pousse sur le côté, œufs battus, brouille 1 min, mélange.'],
    [3,'Riz cuit, 3 min en écrasant les paquets.'],
    [2,'Maquereau émietté + soja + sriracha + ail + paprika, 1–2 min SEULEMENT.']],
 warn:'~34 g de lipides (le maquereau est un poisson gras — c’est le but : oméga-3). Pas d’autre gras sur ce repas.'},
{id:'cabillaudsriracha',n:'Cabillaud sriracha-miel, riz',emoji:'🐟',plats:1,t:18,base:'riz',est:true,kcal:1030,p:68,g:158,l:14,
 ing:['180 g riz thaï sec','300 g cabillaud','2 càs sriracha','1 càs miel','2 càs sauce soja','1 càc ail en poudre','1 càs huile de tournesol'],
 s:[['rc','Riz au rice cooker.'],
    [0,'Sauce dans un bol : sriracha + miel + soja + ail.'],
    [2,'Huile. Cabillaud 3–4 min par face — il est cuit quand il s’émiette à la fourchette.'],
    [1,'Verse la sauce, 1 min en arrosant le poisson.'],
    [0,'Sur le riz.']],
 notes:['14 g de lipides — un des plats les plus propres du répertoire.']},
{id:'pdtpoulet',n:'Poêlée poulet - pommes de terre dorées',emoji:'🥔',plats:1,t:25,est:true,kcal:950,p:72,g:110,l:22,
 ing:['600 g pommes de terre','300 g filet de poulet en morceaux','1 oignon émincé','1 càc paprika fumé','1 càc ail en poudre','½ càc cumin','1 càs + ½ càs huile de tournesol','sel, poivre'],
 s:[[0,'PDT en cubes de 2 cm, dans un saladier + 2 càs d’eau, film troué : MICRO-ONDES 8 min (précuisson sans four).'],
    [3,'1 càs d’huile. Poulet (paprika + ail + cumin + sel) EN 2 FOIS, 4–5 min. Réserve.'],
    [3,'½ càs d’huile. Les PDT précuites 5–6 min SANS toucher pour dorer, puis remue.'],
    [2,'Oignon 2 min, remets le poulet, mélange 1 min.']],
 notes:['La précuisson micro-ondes remplace le four : dedans fondant, dehors doré à la poêle.']},
{id:'gnocchis',n:'Gnocchis sautés crème-champignons, poulet',emoji:'🥟',plats:1,t:18,est:true,kcal:1040,p:63,g:128,l:25,
 ing:['400 g gnocchis (frais, rayon pâtes)','200 g filet de poulet en morceaux','150 g champignons en lamelles','50 g crème légère épaisse','1 càs sauce soja','1 càc paprika fumé','1 càc ail en poudre','1 càs huile de tournesol'],
 s:[[3,'Huile. Poulet 4 min. Réserve.'],
    [2,'Champignons 4–5 min jusqu’à évaporation.'],
    [3,'Gnocchis DIRECTEMENT à la poêle (sans les bouillir !), 5–6 min — ils dorent et croustillent.'],
    [1,'Crème + soja + paprika + ail + 3 càs d’eau, remets le poulet, 2 min. Jamais bouillir.']],
 notes:['Les gnocchis poêlés sans pré-cuisson = croustillant dehors, moelleux dedans. Plus rapide que des pâtes.']},
{id:'wrapspoulet',n:'Wraps chauds poulet-avocat',emoji:'🌯',plats:1,t:15,est:true,kcal:995,p:73,g:100,l:30,
 ing:['3 tortillas de blé','250 g filet de poulet en lanières','½ avocat','1 tomate crue en dés','salade','1 càs sriracha + 1 càc miel + 1 càs sauce soja','1 càc paprika fumé','1 càs huile de tournesol'],
 s:[[3,'Huile. Poulet (paprika, sel, poivre) 4–5 min. Nappe de sriracha-miel-soja 1 min.'],
    [2,'Tortillas 20 secondes par face à la poêle (ou 15 s micro-ondes).'],
    [0,'Monte : avocat écrasé, poulet, tomate, salade. Roule serré.']],
 notes:['Crudités OK maintenant que les plats froids sont réhabilités — ici le poulet est chaud, le reste frais.']},
{id:'udonsautes',n:'Udon sautés poulet-œuf',emoji:'🍜',plats:1,t:15,est:true,kcal:1065,p:67,g:128,l:26,
 ing:['400 g nouilles udon précuites','200 g filet de poulet en lanières','1 œuf','½ oignon émincé','1 carotte en julienne','2 càs sauce soja','1 càs sauce huîtres','1 càc miel','1 càs huile de tournesol','1 càc huile de sésame (hors du feu)'],
 s:[[0,'Sauce dans un bol : soja + huîtres + miel.'],
    [3,'Huile. Poulet 4 min. Réserve.'],
    [2,'Oignon + carotte 3 min. Pousse, œuf battu, brouille 1 min.'],
    [3,'Udon 2 min en séparant les nouilles (1 càs d’eau si elles collent).'],
    [2,'Remets le poulet + la sauce, 1–2 min. Sésame HORS du feu.']]},
{id:'semoulebowl',n:'Bol semoule-porc aux carottes (couscous express)',emoji:'🍲',plats:1,t:20,est:true,kcal:1180,p:76,g:145,l:27,
 ing:['170 g semoule sèche','250 g émincé de porc','2 carottes en rondelles fines','1 oignon émincé','½ cube bouillon','1 càc cumin','½ càc curcuma','1 càc paprika','1 càs huile de tournesol','200 ml d’eau bouillante (pour la semoule)'],
 s:[[3,'Bouilloire/casserole : eau bouillante + ½ cube. Verse sur la semoule, couvre 5 min, égrène à la fourchette.'],
    [3,'Huile. Porc EN 2 FOIS, 4 min. Réserve.'],
    [2,'Oignon + carottes 5–6 min (2 càs d’eau pour aider).'],
    [2,'Remets le porc + cumin + curcuma + paprika, 1 min. Sur la semoule.']],
 notes:['Ta semoule du stock dormait — c’est le féculent le plus rapide du placard : 5 min sans cuisson.']},
{id:'pouletskyr',n:'Poulet sauce skyr-moutarde, pâtes (TEST)',emoji:'🍗',plats:1,t:20,base:'pates',est:true,kcal:1090,p:96,g:130,l:15,
 ing:['170 g pâtes sèches','250 g filet de poulet en morceaux','150 g skyr','2 càs moutarde à l’ancienne','100 ml d’eau de cuisson des pâtes','1 càs sauce soja','1 càc paprika fumé','1 càc ail en poudre','1 càs huile de tournesol'],
 s:[[3,'Pâtes dans la casserole. GARDE une louche d’eau de cuisson.'],
    [3,'Huile. Poulet 4–5 min. Réserve.'],
    [2,'Déglace avec l’eau de cuisson, gratte les sucs. COUPE le feu.'],
    [0,'HORS DU FEU (important, sinon le skyr tranche) : skyr + moutarde + soja + paprika + ail. Fouette 30 s.'],
    [1,'Remets le poulet 1 min max, juste pour réchauffer. Verse sur les pâtes.']],
 warn:'TON TEST skyr-en-sauce : la crème remplacée par du skyr = 96 g de protéines et 15 g de lipides. Si le goût te va, on décline le principe.',
 notes:['Le skyr est MÉLANGÉ (moutarde + soja + paprika) — pas un laitage pur. Règle d’or : jamais au-dessus du niveau 1.']},
{id:'steakskyrpoivre',n:'Steaks, sauce poivre-skyr, riz (TEST)',emoji:'🥩',plats:1,t:15,base:'riz',est:true,kcal:1190,p:74,g:140,l:32,
 ing:['170 g riz thaï sec','2 steaks hachés 10 %','100 g skyr','3 càs sauce poivre','1 càs sauce soja','1 càc ail en poudre','3 càs d’eau'],
 s:[['rc','Riz au rice cooker.'],
    [3,'Steaks surgelés sans huile, 4 min par face. Sors-les, vide le gras.'],
    [2,'Déglace : eau + sauce poivre + soja + ail, gratte, 1 min. COUPE le feu.'],
    [0,'HORS DU FEU : incorpore le skyr en fouettant.'],
    [1,'Steaks hachés à la spatule, remets 1 min. Sur le riz.']],
 notes:['Ton duo crème-poivre, version skyr : le crémeux sans les 17 g de lipides de la crème.']},
{id:'pokesaumon',n:'Poke bowl saumon (froid)',emoji:'🥗',plats:1,t:15,froid:true,est:true,noswapf:true,kcal:980,p:48,g:140,l:22,
 ing:['160 g riz thaï sec (cuit puis refroidi)','150 g saumon fumé (ou saumon poêlé de la veille, froid)','½ concombre en dés','1 carotte râpée','¼ avocat','2 càs sauce soja','1 càc miel','1 càc vinaigre de riz (ou balsamique)','1 càc huile de sésame','sésame doré'],
 s:[['rc','Riz au rice cooker, puis étale-le pour qu’il refroidisse vite (ou riz de la veille).'],
    [0,'Sauce : soja + miel + vinaigre + huile de sésame.'],
    [0,'Bol : riz froid, saumon, concombre, carotte, avocat. Sauce par-dessus, sésame.']],
 notes:['Ton premier plat FROID officiel (réhabilités le 24/08). Parfait télétravail : zéro cuisson si le riz est de la veille.']},
{id:'saladepatesthon',n:'Salade de pâtes au thon (froide)',emoji:'🥗',plats:1,t:15,base:'pates',froid:true,est:true,kcal:1075,p:95,g:130,l:17,
 ing:['170 g pâtes sèches','2 boîtes de thon au naturel égoutté (280 g)','12 tomates cerises coupées en deux','½ concombre en dés','½ oignon rouge émincé fin','1 càs huile d’olive','1 càc moutarde à l’ancienne','1 càs vinaigre balsamique','sel, poivre, herbes de Provence'],
 s:[[3,'Pâtes dans la casserole. Égoutte, passe sous l’eau froide 30 s pour stopper la cuisson.'],
    [0,'Vinaigrette : huile + moutarde + vinaigre + sel + poivre + herbes.'],
    [0,'Mélange tout. Encore meilleur après 1 h de frigo — se prépare la veille.']],
 notes:['95 g de protéines pour 17 g de lipides : le meilleur ratio du catalogue. Meal prep parfait (2 jours au frigo).']},
{id:'wrapfroid',n:'Wraps froids poulet-crudités (télétravail)',emoji:'🌯',plats:1,t:10,froid:true,est:true,kcal:950,p:62,g:98,l:20,
 ing:['3 tortillas de blé','200 g filet de poulet (cuit, froid — de la veille)','salade','1 tomate en dés','½ concombre en bâtonnets','2 càs skyr + 1 càc moutarde + 1 càc sriracha (sauce)','sel, poivre'],
 s:[[0,'Sauce : skyr + moutarde + sriracha, fouettée 20 s.'],
    [0,'Tartine chaque tortilla, poulet froid effiloché, crudités.'],
    [0,'Roule serré, coupe en deux. Zéro cuisson si le poulet est du meal prep.']]},
{id:'bavettesoja',n:'Bavette sauce oignon-soja, riz',emoji:'🥩',plats:1,t:20,base:'riz',est:true,kcal:1020,p:56,g:150,l:17,
 ing:['180 g riz thaï sec','200 g bavette (ou bœuf à sauter)','1 oignon émincé','3 càs sauce soja','1 càc miel','1 càc ail en poudre','4 càs d’eau','poivre'],
 s:[['rc','Riz au rice cooker. Sors la viande 20 min avant.'],
    [3,'Poêle vide, SANS huile, 4–5 min à blanc. Bavette 2 min par face (saignant). Sors-la, REPOS 3 min.'],
    [2,'Oignon 3 min dans le gras rendu, gratte les sucs.'],
    [2,'Eau + soja + miel + ail, réduis 2 min.'],
    [0,'Tranche la bavette dans le sens CONTRAIRE des fibres, remets 30 s dans la sauce. Sur le riz.']],
 notes:['La bavette = le morceau à sauter le moins cher au rayon anti-gaspi Intermarché.']},
{id:'crevettesail',n:'Crevettes ail-sriracha, riz',emoji:'🦐',plats:1,t:15,base:'riz',est:true,kcal:1040,p:71,g:150,l:14,
 ing:['180 g riz thaï sec','300 g crevettes décortiquées (surgelées OK, décongelées)','2 càs sriracha','1 càs miel','2 càs sauce soja','2 càc ail en poudre','1 càs huile de tournesol','½ oignon émincé'],
 s:[['rc','Riz au rice cooker.'],
    [0,'ÉPONGE bien les crevettes (surtout si décongelées — sinon elles bouillent).'],
    [3,'Huile. Oignon 2 min, puis crevettes 2 min par face — roses = cuites, pas plus.'],
    [2,'Sriracha + miel + soja + ail, 1 min en nappant.'],
    [0,'Sur le riz.']],
 warn:'Les crevettes cuisent en 4 min TOTAL — trop cuites = caoutchouc.'},
{id:'veaucreme',n:'Escalope de veau crème-champignons, pâtes',emoji:'🥩',plats:1,t:20,base:'pates',est:true,kcal:1090,p:80,g:125,l:22,
 ing:['170 g pâtes sèches','250 g escalope de veau en lanières','150 g champignons en lamelles','60 g crème légère épaisse','100 ml d’eau de cuisson','1 càs sauce soja','1 càc paprika fumé','1 càc ail en poudre','1 càs huile de tournesol'],
 s:[[3,'Pâtes dans la casserole. GARDE une louche d’eau.'],
    [3,'Huile. Veau 2–3 min par face SEULEMENT (trop cuit = semelle). Réserve.'],
    [2,'Champignons 5 min jusqu’à évaporation.'],
    [1,'Crème + eau de cuisson + soja + paprika + ail, 2 min. Remets le veau 1 min.'],
    [0,'Sur les pâtes.']]},
{id:'indomie',n:'Indomie sautées poulet-œuf',emoji:'🍜',plats:1,t:15,est:true,kcal:1110,p:69,g:112,l:37,
 ing:['2 paquets de nouilles Indomie (ton stock)','200 g filet de poulet en lanières','1 œuf','½ oignon émincé','1 carotte en julienne','les sachets d’assaisonnement (⚠️ 1 seul sachet d’huile sur les 2)','1 càs sauce soja'],
 s:[[3,'Casserole : nouilles 3 min dans l’eau bouillante, égoutte.'],
    [3,'Poulet 4 min sans huile ajoutée. Réserve.'],
    [2,'Oignon + carotte 3 min. Pousse, œuf battu, brouille 1 min.'],
    [2,'Nouilles + assaisonnements (1 SEUL sachet d’huile) + soja + poulet, 2 min.']],
 warn:'~37 g de lipides (les Indomie sont des nouilles frites) — déjà réduit en jetant un sachet d’huile sur deux. Pas d’autre gras ce repas-là.'},
{id:'lentillesbowl',n:'Bowl lentilles-riz curry-coco, œuf',emoji:'🍛',plats:1,t:30,base:'riz',est:true,noswapf:true,kcal:1110,p:52,g:165,l:15,
 ing:['150 g lentilles vertes sèches (ton stock)','100 g riz thaï sec','80 ml lait de coco Kara','1 càc curry','½ càc curcuma','1 oignon émincé','1 carotte en dés','½ cube bouillon','1 œuf','1 càs sauce soja'],
 s:[[3,'Casserole : lentilles + carotte + bouillon + eau (2 cm au-dessus), 25 min à petit bouillon. (Passif — lance le riz pendant ce temps.)'],
    ['rc','Riz au rice cooker.'],
    [2,'Poêle : oignon 3 min. Ajoute lentilles égouttées + coco + curry + curcuma + soja, 3 min.'],
    [2,'Œuf au plat à côté.'],
    [0,'Bol : riz, lentilles curry, œuf par-dessus.']],
 notes:['Tes lentilles vertes du stock (pas les corail que tu n’aimes pas). 25 min de cuisson mais passives — tu ne fais rien pendant.']}
];

/* Sauces — classées par lipides (quantités pour 1 plat) · kcal ≈ estimation à confirmer */
var SAUCES=[
{n:'Aigre-douce',l:0,k:60,compo:'Sauce du commerce — ~4 càs (60 g) par plat (estimation)'},
{n:'Déglacée au bouillon',l:0,k:50,compo:'6 càs eau + ¼ cube bouillon bœuf + 2 càs soja + 1 càc miel + 1 càc ail + 1 càc moutarde ancienne'},
{n:'Soja-miel-ail-sriracha',l:1,k:40,compo:'3 càs soja + 1 càc miel + 1 càc ail poudre + 1 càs sriracha + 2 càs eau'},
{n:'Gochujang',l:1,k:55,compo:'1 càs gochujang + 1 càs sauce huîtres + 1 càs soja + 1 càc miel + ail'},
{n:'Tomate + ail + herbes',l:2,k:60,compo:'Sauce tomate + ail poudre + herbes de Provence + 1 càs soja'},
{n:'Moutarde ancienne + soja + bouillon',l:2,k:60,compo:'Sans crème : 200 ml eau de cuisson + ½ cube bouillon + 3 càs moutarde ancienne + 1 càs soja + ail'},
{n:'Tandoori Patak’s',l:4,k:90,compo:'Sauce du commerce — ~3 càs (50 g) par plat (estimation)'},
{n:'Poivre LÉGÈRE (sans crème)',l:7,k:90,compo:'4 càs sauce poivre + 100 ml d’eau + 1 càs soja + 1 càc ail — ton kiff, utilisable plus souvent (la version crème reste en bas de liste)'},
{n:'Curry-coco',l:11,k:130,compo:'80 ml lait de coco Kara + curry + soja + miel + ail',riche:true},
{n:'Crème-moutarde ancienne',l:17,k:210,compo:'100 g crème légère + 3 càs moutarde + 200 ml eau de cuisson + ½ cube bouillon + 1 càs soja + 2 càc ail',riche:true},
{n:'Crème-tomate-basilic (rosée)',l:17,k:220,compo:'100 g crème + 60 g concentré tomate + 200 ml eau de cuisson + 1 càs soja + ail + herbes + basilic hors du feu',riche:true},
{n:'Crème-champignons',l:18,k:230,compo:'120–150 g crème légère + champignons + oignon + 1 càs soja + paprika fumé + ail',riche:true},
{n:'Crème-poivre',l:20,k:250,compo:'80–100 g crème épaisse + 3 càs sauce poivre + 100 ml eau + 1 càs soja + ail + paprika',riche:true}
];

/* Diagnostics sauces */
var DIAG=[
['Trop liquide','Pas assez réduit','Mijoter niveau 1 sans couvercle 2 min de plus'],
['Pas assez de volume','Trop peu de liquide','200 ml d’eau de cuisson des pâtes'],
['Granuleuse / tranchée','Crème chauffée trop fort','Niveau 1 uniquement, ne jamais bouillir'],
['Attache au fond','Feu trop fort','Baisser, 2 càs d’eau, décoller les sucs'],
['Trop salée','—','1 càc de miel'],
['Sans goût','—','Ail en poudre + herbes + 1 càs de sauce soja'],
['Goût « crème pure »','—','Paprika fumé + 1 càs de sauce soja — non négociable']];

/* Snacks — le critère : beaucoup de glucides, peu de lipides */
var SNACKS=[
{id:'compote',n:'Compote Charles & Alice',emoji:'🍎',k:90,g:20,p:0,l:0,note:'JAMAIS « sans sucres ajoutés » (−40 % de l’intérêt). Gourde > coupelle. 2/jour max : une au petit-déj (créatine), une 30–45 min avant la séance.'},
{id:'banane',n:'Banane',emoji:'🍌',k:105,g:25,p:1,l:0,note:'Le glucide de poche.'},
{id:'bcuillere',n:'Biscuits cuillère / boudoirs ×4',emoji:'🍪',k:90,g:18,p:2,l:1,note:'La base validée — même famille, même usage : ~74 g de glucides / 4 g de lipides aux 100 g.'},
{id:'madeleine',n:'Madeleine (1)',emoji:'🧁',k:110,g:13,p:1,l:5,note:'Gérable à l’UNITÉ, pas au paquet (20 g de lipides / 100 g).'},
{id:'pancake',n:'Pancake protéiné (1)',emoji:'🥞',k:149,g:21.5,p:9.2,l:2.7,note:'Ta recette batch ~15 pancakes (fiche 🥞 dans Recettes) — macros mesurées. Cuis tout le dimanche, boîte au frigo, 1-2 en snack.'}];

/* Extérieur / resto — estimations par unité, cumulables dans la Journée (décision 24/08) */
var RESTO=[
{id:'kebab',n:'Kebab (sandwich)',emoji:'🥙',k:750,p:40,g:60,l:35},
{id:'tacos',n:'French tacos (M)',emoji:'🌯',k:950,p:45,g:90,l:45},
{id:'pizza',n:'Pizza entière',emoji:'🍕',k:1800,p:65,g:200,l:75},
{id:'burger',n:'Burger',emoji:'🍔',k:550,p:28,g:40,l:28},
{id:'sushi',n:'Sushi/maki ×12',emoji:'🍣',k:600,p:28,g:90,l:10},
{id:'frites',n:'+ Frites (portion)',emoji:'🍟',k:400,p:5,g:50,l:18}];

/* Table de snacks « vitrine » (pane Snacks) — /100 g */
var SNACKS_TABLE=[
['Meringues',95,0],['Biscuits cuillère / boudoirs ⭐',74,4],['Barquettes abricot/fraise',72,7],
['Nougat tendre',70,8],['Génoise / gâteau de Savoie',65,6],
['Petits-beurre',null,12],['Madeleines',null,20],['Quatre-quarts',null,20]];

/* Calculateur — aliments /100 g sauf unité précisée : [kcal, P, L, G] */
var CF={
 prot:{poulet:['Filet de poulet',110,23,2,0],porc:['Émincé de porc',175,21,6,0],
  steak:['Steak haché 10 % (1 = 125 g)',182,20,10,0],fauxfilet:['Faux-filet',190,21,11.5,0],
  thon:['Thon au naturel (1 boîte = 140 g)',115,26,1,0],cabillaud:['Cabillaud',80,18,0.7,0],saumon:['Saumon',200,20,13,0],crevettes:['Crevettes décortiquées',85,19,0.8,0],oeuf:['Œuf (unité)',78,6.5,5,0.5]},
 fec:{riz:['Riz thaï sec',355,7,1,78],pates:['Pâtes sèches',360,12.5,1.5,72]},
 leg:{champignons:['Champignons',22,3,0.3,1],haricots:['Haricots verts',31,1.8,0.2,5],oignon:['Oignon',40,1.1,0.1,8],carotte:['Carotte',41,0.9,0.2,9],poivron:['Poivron',26,1,0.3,5]},
 huile:['1 càs huile de tournesol',90,0,10,0]
};

return {CIBLES:CIBLES,PDJ:PDJ,SHAKER:SHAKER,R:R,SAUCES:SAUCES,DIAG:DIAG,SNACKS:SNACKS,SNACKS_TABLE:SNACKS_TABLE,RESTO:RESTO,CF:CF};
})();
